[package]
name = "flashcards"
version = "0.1.0"
edition = "2021"

[dependencies]
clap =  { version = "4.4.6", features = ["derive"] }
flash_card_parser = { git = "https://github.com/Lukas412/FlashCardParser.git" }
anyhow = "1.0.75"
serde_json = "1.0.107"
